### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by xreider** [sweetalert2/sweetalert2#2261]
"@sweetalert2/themes": "^5.0.0",
    "sweetalert2": "^11.0.11",

    "@babel/core": "^7.14.3",
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "@babel/preset-env": "^7.14.2",
    "@babel/runtime": "^7.14.0",
    "babel-loader": "^8.2.2",
    "babel-plugin-minify-builtins": "^0.5.0",
    "clean-webpack-plugin": "^4.0.0-alpha.0",
    "concurrently": "^6.2.0",
    "css-loader": "^5.2.6",
    "css-minimizer-webpack-plugin": "^3.0.0",
    "mini-css-extract-plugin": "^1.6.0",
    "nodemon": "^2.0.7",
    "prettier": "^2.3.0",
    "sass": "^1.34.0",
    "sass-loader": "^11.1.1",
    "style-loader": "^2.0.0",
    "webpack": "^5.37.1",
    "webpack-cli": "^4.7.0"

## Current behavior

[0] DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
[0]
[0] Recommendation: math.div($number, $number * 0 + 1)
[0]
[0] More info and automated migrator: https://sass-lang.com/d/slash-div
[0]
[0]     ╷
[0] 513 │   @return $number / ($number * 0 + 1);
[0]     │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0]     ╵
[0]     node_modules\sweetalert2\src\scss\_core.scss 513:11  strip-units()
[0]     node_modules\sweetalert2\src\scss\_core.scss 515:13  @import
[0]     node_modules\sweetalert2\src\scss\_theming.scss 8:9  @import
[0]     node_modules\sweetalert2\src\sweetalert2.scss 4:9    @import
[0]     assets\styles\common\sweetalert2.scss 1:9            @import
[0]     assets\styles\index.scss 26:9                        root stylesheet
[0]
[0] DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.        
[0]
[0] Recommendation: math.div(strip-units($swal2-icon-size), 5)
[0]
[0] More info and automated migrator: https://sass-lang.com/d/slash-div
[0]
[0]     ╷
[0] 515 │ $icon-zoom: strip-units($swal2-icon-size) / 5;
[0]     │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0]     ╵
[0]     node_modules\sweetalert2\src\scss\_core.scss 515:13  @import
[0]     node_modules\sweetalert2\src\scss\_theming.scss 8:9  @import
[0]     node_modules\sweetalert2\src\sweetalert2.scss 4:9    @import
[0]     assets\styles\common\sweetalert2.scss 1:9            @import
[0]     assets\styles\index.scss 26:9                        root stylesheet
[0]
[0] assets by status 1.36 MiB [cached] 2 assets
[0] Entrypoint bundle 1.36 MiB = bundle.css 89.2 KiB bundle.js 1.27 MiB
[0] cached modules 777 KiB (javascript) 89.2 KiB (css/mini-extract) 1.19 KiB (runtime) [cached] 557 modules[0] ./assets/styles/index.scss 50 bytes [built]
[0] webpack 5.37.1 compiled successfully in 457 ms

**Comment by limonte** [comment]
The issue was fixed yesterday https://github.com/sweetalert2/sweetalert2/releases/tag/v11.0.12

**Comment by elvispdosreis** [comment]
I tested with version 11.0.16 and even then presented the same error

*"sweetalert2": "^11.0.16"*

**Comment by limonte** [comment]
Sorry fellas, I misread the issue description. The issue is actually you need to upgrade the `sass` dependency to at least `1.33.0`.

**Comment by paulpottertasd** [comment]
Has this been resolved? Still getting it with 11.0.16. Thanks!

**Comment by CyberCookie** [comment]
same error with sass 1.34.1

**Comment by limonte** [comment]
Guys, instead of commenting with such comments, please put some effort in reporting a proper issue with the simple repo where the issue can be seen. Thanks.
